export const log_actions = [
    { "action_code": "SIGNUP"},
    { "action_code": "SIGNIN"},
    { "action_code": "REQUEST_PASSWORD_RESET"},
    { "action_code": "RESET_PASSWORD"},
    { "action_code": "IMPORT_DEFAULT_DATA"},
    { "action_code": "READ_ALERT" },
    { "action_code": "CREATE_ALERT" },
    { "action_code": "UPDATE_ALERT" },
    { "action_code": "DELETE_ALERT" },
    { "action_code": "READ_ALERT_TYPE" },
    { "action_code": "CREATE_ALERT_TYPE" },
    { "action_code": "UPDATE_ALERT_TYPE" },
    { "action_code": "DELETE_ALERT_TYPE" },
    { "action_code": "READ_AUDIT_LOG" },
    { "action_code": "CREATE_AUDIT_LOG" },
    { "action_code": "UPDATE_AUDIT_LOG" },
    { "action_code": "DELETE_AUDIT_LOG" },
    { "action_code": "READ_AUTH" },
    { "action_code": "CREATE_AUTH" },
    { "action_code": "UPDATE_AUTH" },
    { "action_code": "DELETE_AUTH" },
    { "action_code": "READ_AUTHOR" },
    { "action_code": "CREATE_AUTHOR" },
    { "action_code": "UPDATE_AUTHOR" },
    { "action_code": "DELETE_AUTHOR" },
    { "action_code": "READ_BOOK" },
    { "action_code": "CREATE_BOOK" },
    { "action_code": "UPDATE_BOOK" },
    { "action_code": "DELETE_BOOK" },
    { "action_code": "READ_BOOK_COLLECTION" },
    { "action_code": "CREATE_BOOK_COLLECTION" },
    { "action_code": "UPDATE_BOOK_COLLECTION" },
    { "action_code": "DELETE_BOOK_COLLECTION" },
    { "action_code": "READ_BOOK_LIST" },
    { "action_code": "CREATE_BOOK_LIST" },
    { "action_code": "UPDATE_BOOK_LIST" },
    { "action_code": "DELETE_BOOK_LIST" },
    { "action_code": "ADD_BOOK_TO_LIST"},
    { "action_code": "REMOVE_BOOK_FROM_LIST"},
    { "action_code": "READ_BOOK_STATUS" },
    { "action_code": "CREATE_BOOK_STATUS" },
    { "action_code": "UPDATE_BOOK_STATUS" },
    { "action_code": "DELETE_BOOK_STATUS" },
    { "action_code": "READ_EDITORIAL" },
    { "action_code": "CREATE_EDITORIAL" },
    { "action_code": "UPDATE_EDITORIAL" },
    { "action_code": "DELETE_EDITORIAL" },
    { "action_code": "READ_EQUIPMENT" },
    { "action_code": "CREATE_EQUIPMENT" },
    { "action_code": "UPDATE_EQUIPMENT" },
    { "action_code": "DELETE_EQUIPMENT" },
    { "action_code": "READ_FEE" },
    { "action_code": "CREATE_FEE" },
    { "action_code": "UPDATE_FEE" },
    { "action_code": "DELETE_FEE" },
    { "action_code": "READ_FEE_STATUS" },
    { "action_code": "CREATE_FEE_STATUS" },
    { "action_code": "UPDATE_FEE_STATUS" },
    { "action_code": "DELETE_FEE_STATUS" },
    { "action_code": "READ_FEE_TYPE" },
    { "action_code": "CREATE_FEE_TYPE" },
    { "action_code": "UPDATE_FEE_TYPE" },
    { "action_code": "DELETE_FEE_TYPE" },
    { "action_code": "READ_GENDER" },
    { "action_code": "CREATE_GENDER" },
    { "action_code": "UPDATE_GENDER" },
    { "action_code": "DELETE_GENDER" },
    { "action_code": "READ_LOAN" },
    { "action_code": "CREATE_LOAN" },
    { "action_code": "UPDATE_LOAN" },
    { "action_code": "DELETE_LOAN" },
    { "action_code": "REQUEST_LOAN_RENEWAL" },
    { "action_code": "FINISH_LOAN" },
    { "action_code": "READ_LOG_ACTION" },
    { "action_code": "CREATE_LOG_ACTION" },
    { "action_code": "UPDATE_LOG_ACTION" },
    { "action_code": "DELETE_LOG_ACTION" },
    { "action_code": "READ_RESERVATION" },
    { "action_code": "CREATE_RESERVATION" },
    { "action_code": "UPDATE_RESERVATION" },
    { "action_code": "DELETE_RESERVATION" },
    { "action_code": "READ_ROLE" },
    { "action_code": "CREATE_ROLE" },
    { "action_code": "UPDATE_ROLE" },
    { "action_code": "DELETE_ROLE" },
    { "action_code": "ADD_PERMISSION_TO_ROLE"},
    { "action_code": "REMOVE_PERMISSION_FROM_ROLE"},
    { "action_code": "READ_ROOM" },
    { "action_code": "CREATE_ROOM" },
    { "action_code": "UPDATE_ROOM" },
    { "action_code": "DELETE_ROOM" },
    { "action_code": "READ_ROOM_LOCATION" },
    { "action_code": "CREATE_ROOM_LOCATION" },
    { "action_code": "UPDATE_ROOM_LOCATION" },
    { "action_code": "DELETE_ROOM_LOCATION" },
    { "action_code": "READ_ROOM_STATUS" },
    { "action_code": "CREATE_ROOM_STATUS" },
    { "action_code": "UPDATE_ROOM_STATUS" },
    { "action_code": "DELETE_ROOM_STATUS" },
    { "action_code": "READ_USER" },
    { "action_code": "CREATE_USER" },
    { "action_code": "UPDATE_USER" },
    { "action_code": "DELETE_USER" }
  ]
  