services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server_docker
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - mongodb  # Start MongoDB before
    volumes:
      - ./public/images:/app/public/images # Data persistance
    networks:
      - app-network
  mongodb:
    image: mongo:6
    container_name: mongo_db_docker
    ports:
      - "127.0.0.1:27017:27017"  # MongoDB port
      #- "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db  # Data persistance
    networks:
      - app-network
  mongoexpress:
    image: mongo-express
    container_name: mongo_express_docker
    restart: always
    env_file:
      - .env
    ports:
      - "${ME_CONFIG_PORT}:${ME_CONFIG_PORT}"
    depends_on:
      - mongodb  # Start MongoDB before
    networks:
      - app-network
volumes:
  mongodb_data:
networks:
  app-network: